Projeto extensionista  do curso Tópicos de Big Data em Python
Faculdate Estacio de Sá RJ (Unesa)
Aluno: José Roberto Duarte Hegendorne
Matrícula: 202502214154
Curso Presencial
Professora: Simone Gama
Período: 1ª semestre 2026

Dados do Sistema de Bilhetagem Eletrônica

URL dos dados analizados: 
https://dadosabertos.rj.gov.br/dataset/setram_sbe

Repositório de dados baixados https://dadosabertos.rj.gov.br/dataset/setram_sbe
link do repósitorio do drive é  https://drive.google.com/drive/folders/1486i6aBSUVuyrD6bISm0qYGZs-eIhK71?usp=sharing

os arquivos são distribuidos com a movimentação diaria do bilhete unico, fazer o carregamento disso, em grandes periodos , requer um hardware com mais recursos


Dicionario de Dados dos arquivos originais: 
    Cartão Hash: 
        Sequência única de caracteres gerada a partir do Nº Cartão. 
    Data da Transação:
        Data e hora do processamento da transação.
    Data do Processamento:  
        Data e hora do processamento da transação.
    Descrição da Aplicação:    
        Código da aplicação do cartão 
            - 100 - Expresso
            - 114 - Siga Viagem Supervia, 
            - 115 - Siga Viagem Metrô, 
            - 400 - Vale-transporte, 
            - 450 - Empresarial, 
            - 820 - Gratuidade de Morador de Paquetá/Ilha Grande, 
            - 80 QRCode Unitário
        Descrição da Aplicação
    Linha - 
        Número e nome da Linha.
    Nº Carro:
         Número da estação ou do carro onde a transação foi realizada.
    Nº Cartão:
        Número externo do cartão do usuário. Informação anonimizada para atender a LGPD, conforme exemplo a seguir: 1091xxxxxx713.
    Nº Validador:
        Número do validador utilizado na transação.
    Operadora:
          Nome da Operadora de transporte. Informação anonimizada para as Vans para atender a LGPD, conforme exemplo a seguir: VAN560001-LUISA MAxxxxxxxx
    Sentido:
        Código do sentido da linha (0 - não informado, 1 - ida, 2 - volta).
    Sindicato:
        Nome do sindicato
    Vl Linha
        Valor da linha da operadora de transporte.
    Vl Subsídio
        Valor do subsídio.
    Vl Trans
        Valor descontado no cartão do usuário.
 
    
      


Variaveis declaradas:
    Po - pandas (referente ao panda do filme , po)
    Bu_total - variavel que recebe o CSV sem tratamento
    Bu - Variavel com Csv tratado
    colunas - lista os campos que irei utilizar

Instanciando o panda  com Nome Po

In [87]:
import pandas as Po

 Fazendo carregamento do ARQUIVO CSV
 a separação dos dados esta sendo feito por ";"

In [88]:
Bu_total = Po.read_csv(r"i:\facul\csv\transacao_be_publico_2026_03_15.csv\TRANSACAO_BE_PUBLICO_2026_03_15.csv", encoding='utf8', sep=';',nrows=5000)

Estou estruturando os campos do arquivo CSV à serem tratados,
Removi rash e o numero do cartão do passageiro porque eles esconderam o numero real com caracteres X
Nº  2024XXXXX3128

In [89]:
colunas = [
    "Data do Processamento",    
    "Data da Transação",
    "Descrição da Aplicação",
    "Sentido",
    "Nº Validador",
    "Sindicato",
    "Operadora",
    "Linha",
    "Nº Carro",
    "Nº Validador",
    "Vl Linha",
    "Vl Trans",
    "Vl Subsídio"
]

Filtrando os campos a serem utilizados

In [90]:
Bu = Bu_total[colunas]

TRATAMENTO DOS DADOS 
----------------------------------------------------------

Renomeando as colunas das tabelas, Removendo espaços , caracteres especiais  utilizando .rename(columns={"xx":"yy"})

In [91]:
Bu.rename(columns={"Data do Processamento": "Data_do_Processamento",    
    "Data da Transação":"Data_da_Transacao",
    "Descrição da Aplicação":"Descricao_da_Aplicacao",
    "Nº Validador":"N_Validador",
    "Nº Carro": "N_Carro",
    "Nº Validador":"N_Validador",
    "Vl Linha":"Vl_Linha",
    "Vl Trans":"Vl_Trans",
    "Vl Subsídio":"Vl_Subsidio"}, inplace=True)    # inplace=True é necessario para manter salvo as mudanças

In [92]:
#exibindo as inforamações da tabela
Bu.info()
Bu

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 13 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Data_do_Processamento   5000 non-null   str
 1   Data_da_Transacao       5000 non-null   str
 2   Descricao_da_Aplicacao  5000 non-null   str
 3   Sentido                 0 non-null      float64
 4   N_Validador             5000 non-null   int64
 5   Sindicato               5000 non-null   str
 6   Operadora               5000 non-null   str
 7   Linha                   5000 non-null   str
 8   N_Carro                 5000 non-null   int64
 9   N_Validador             5000 non-null   int64
 10  Vl_Linha                5000 non-null   str
 11  Vl_Trans                5000 non-null   str
 12  Vl_Subsidio             0 non-null      float64
dtypes: float64(2), int64(3), str(8)
memory usage: 507.9 KB

,Data_do_Processamento,Data_da_Transacao,Descricao_da_Aplicacao,Sentido,N_Validador,Sindicato,Operadora,Linha,N_Carro,N_Validador,Vl_Linha,Vl_Trans,Vl_Subsidio
0,15/03/2026 15:54:08,15/03/2026 15:54:08,80-QR CODE UNITÁRIO,NaN,77399,BARCAS,Barcas Rio,PXV-PQ - PRAÇAXV X PAQUETA,17007,77399,"5,00","5,00",NaN
1,15/03/2026 22:42:20,15/03/2026 22:42:20,80-QR CODE UNITÁRIO,NaN,77688,METRÔ RIO,Concessao Metroviaria do Rio de Janeiro S. A.,L2 PVN - Estação Pavuna - Metrô,32208,77688,"7,90","7,90",NaN
2,15/03/2026 08:13:28,15/03/2026 08:13:28,80-QR CODE UNITÁRIO,NaN,77361,METRÔ RIO,Concessao Metroviaria do Rio de Janeiro S. A.,L1 SCP - Estação Siqueira Campos - Metrô,17214,77361,"7,90","7,90",NaN
3,15/03/2026 09:50:49,15/03/2026 09:50:49,80-QR CODE UNITÁRIO,NaN,77536,BARCAS,Barcas Rio,PXV-PQ - PRAÇAXV X PAQUETA,13006,77536,"5,00","5,00",NaN
4,15/03/2026 09:18:08,15/03/2026 09:18:08,80-QR CODE UNITÁRIO,NaN,77536,BARCAS,Barcas Rio,PXV-PQ - PRAÇAXV X PAQUETA,13006,77536,"5,00","5,00",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,15/03/2026 09:29:11,15/03/2026 09:29:11,80-QR CODE UNITÁRIO,NaN,76910,BARCAS,Barcas Rio,PXV-NIT - PRAÇA XV X ARARIBOIA,14018,76910,"5,00","5,00",NaN
4996,15/03/2026 08:12:16,15/03/2026 08:12:16,80-QR CODE UNITÁRIO,NaN,77439,METRÔ RIO,Concessao Metroviaria do Rio de Janeiro S. A.,L1 CTR - Estação Central - Metrô,6116,77439,"7,90","7,90",NaN
4997,15/03/2026 10:26:43,15/03/2026 10:26:43,80-QR CODE UNITÁRIO,NaN,76910,BARCAS,Barcas Rio,PXV-NIT - PRAÇA XV X ARARIBOIA,14018,76910,"5,00","5,00",NaN
4998,15/03/2026 10:58:10,15/03/2026 10:58:10,80-QR CODE UNITÁRIO,NaN,42170,METRÔ RIO,Concessao Metroviaria do Rio de Janeiro S. A.,L1 CTR - Estação Central - Metrô,6117,42170,"7,90","7,90",NaN
4999,15/03/2026 18:52:17,15/03/2026 18:52:17,80-QR CODE UNITÁRIO,NaN,76843,METRÔ RIO,Concessao Metroviaria do Rio de Janeiro S. A.,L4 NSP - Estação Nossa Senhora da Paz,52104,76843,"7,90","7,90",NaN

Tratando o Campo "Sentido"

Sentido:
        Código do sentido da linha (0 - não informado, 1 - ida, 2 - volta).
Tudo que estiver vazio(NaN) receberá 0
Convertendo o campo em Inteiro pois esta como float .astype(int)
precisei arredondar para converter usando .round()

In [93]:

Bu["Sentido"] = Bu["Sentido"].fillna(0) # a função filna do panda preenche o vazio com 0 (zero)
Bu["Sentido"] = Bu["Sentido"].round().astype(int) # arredondando com round e convertendo para inteiro
Bu.head(5) # exibindo somente 5 registros

,Data_do_Processamento,Data_da_Transacao,Descricao_da_Aplicacao,Sentido,N_Validador,Sindicato,Operadora,Linha,N_Carro,N_Validador,Vl_Linha,Vl_Trans,Vl_Subsidio
0,15/03/2026 15:54:08,15/03/2026 15:54:08,80-QR CODE UNITÁRIO,0,77399,BARCAS,Barcas Rio,PXV-PQ - PRAÇAXV X PAQUETA,17007,77399,"5,00","5,00",NaN
1,15/03/2026 22:42:20,15/03/2026 22:42:20,80-QR CODE UNITÁRIO,0,77688,METRÔ RIO,Concessao Metroviaria do Rio de Janeiro S. A.,L2 PVN - Estação Pavuna - Metrô,32208,77688,"7,90","7,90",NaN
2,15/03/2026 08:13:28,15/03/2026 08:13:28,80-QR CODE UNITÁRIO,0,77361,METRÔ RIO,Concessao Metroviaria do Rio de Janeiro S. A.,L1 SCP - Estação Siqueira Campos - Metrô,17214,77361,"7,90","7,90",NaN
3,15/03/2026 09:50:49,15/03/2026 09:50:49,80-QR CODE UNITÁRIO,0,77536,BARCAS,Barcas Rio,PXV-PQ - PRAÇAXV X PAQUETA,13006,77536,"5,00","5,00",NaN
4,15/03/2026 09:18:08,15/03/2026 09:18:08,80-QR CODE UNITÁRIO,0,77536,BARCAS,Barcas Rio,PXV-PQ - PRAÇAXV X PAQUETA,13006,77536,"5,00","5,00",NaN

Tratando valor do subsidio   "Vl Subsídio"  porque há valores vazios (NaN)

In [94]:
Bu["Vl_Subsidio"] = Bu["Vl_Subsidio"].fillna(0) 
Bu.head(5)

,Data_do_Processamento,Data_da_Transacao,Descricao_da_Aplicacao,Sentido,N_Validador,Sindicato,Operadora,Linha,N_Carro,N_Validador,Vl_Linha,Vl_Trans,Vl_Subsidio
0,15/03/2026 15:54:08,15/03/2026 15:54:08,80-QR CODE UNITÁRIO,0,77399,BARCAS,Barcas Rio,PXV-PQ - PRAÇAXV X PAQUETA,17007,77399,"5,00","5,00",0.0
1,15/03/2026 22:42:20,15/03/2026 22:42:20,80-QR CODE UNITÁRIO,0,77688,METRÔ RIO,Concessao Metroviaria do Rio de Janeiro S. A.,L2 PVN - Estação Pavuna - Metrô,32208,77688,"7,90","7,90",0.0
2,15/03/2026 08:13:28,15/03/2026 08:13:28,80-QR CODE UNITÁRIO,0,77361,METRÔ RIO,Concessao Metroviaria do Rio de Janeiro S. A.,L1 SCP - Estação Siqueira Campos - Metrô,17214,77361,"7,90","7,90",0.0
3,15/03/2026 09:50:49,15/03/2026 09:50:49,80-QR CODE UNITÁRIO,0,77536,BARCAS,Barcas Rio,PXV-PQ - PRAÇAXV X PAQUETA,13006,77536,"5,00","5,00",0.0
4,15/03/2026 09:18:08,15/03/2026 09:18:08,80-QR CODE UNITÁRIO,0,77536,BARCAS,Barcas Rio,PXV-PQ - PRAÇAXV X PAQUETA,13006,77536,"5,00","5,00",0.0

tratando os campos que contém data. pois o formato esta em string
mudou o padrão de XX / XX / XXXX para xx-xx-xxxx

In [95]:
Bu["Data_do_Processamento"] = Po.to_datetime(Bu["Data_do_Processamento"], dayfirst=True) # tratando campo data e colocando os dias como primeiro(dayfirst)

Bu["Data_da_Transacao"] = Po.to_datetime(Bu["Data_da_Transacao"], dayfirst=True)

trocando valores  de ","   para "." e convertendo para float

In [96]:
Bu["Vl_Linha"] = Bu["Vl_Linha"].str.replace(",", ".").astype(float)
Bu["Vl_Trans"] = Bu["Vl_Trans"].str.replace(",", ".").astype(float)
Bu.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 13 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Data_do_Processamento   5000 non-null   datetime64[us]
 1   Data_da_Transacao       5000 non-null   datetime64[us]
 2   Descricao_da_Aplicacao  5000 non-null   str
 3   Sentido                 5000 non-null   int64
 4   N_Validador             5000 non-null   int64
 5   Sindicato               5000 non-null   str
 6   Operadora               5000 non-null   str
 7   Linha                   5000 non-null   str
 8   N_Carro                 5000 non-null   int64
 9   N_Validador             5000 non-null   int64
 10  Vl_Linha                5000 non-null   float64
 11  Vl_Trans                5000 non-null   float64
 12  Vl_Subsidio             5000 non-null   float64
dtypes: datetime64[us](2), float64(3), int64(4), str(4)
memory usage: 507.9 KB

Limpando os campos vazio dos campos dos campos que são string

Descricao_da_Aplicacao , Operadora , Linha, Sindicato

In [97]:
Bu["Descricao_da_Aplicacao"] = Bu["Descricao_da_Aplicacao"].str.strip()
Bu["Operadora"] = Bu["Operadora"].str.strip()
Bu["Linha"] = Bu["Linha"].str.strip()
Bu["Sindicato"] = Bu["Sindicato"].str.strip()

Fim do Tratamento , por enquanto

Salvando o arquivo tratado em csv, lembrando que lá em cima eu limitei a 5000 registros

In [98]:
Bu.to_csv(r"i:\facul\csv\dados_tratados_Bu.csv", sep=';', index=False, encoding='latin-1')

Mostra informações gerais do DataFrame (tipos de dados, valores não nulos, etc.)

In [99]:
Bu.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 13 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Data_do_Processamento   5000 non-null   datetime64[us]
 1   Data_da_Transacao       5000 non-null   datetime64[us]
 2   Descricao_da_Aplicacao  5000 non-null   str
 3   Sentido                 5000 non-null   int64
 4   N_Validador             5000 non-null   int64
 5   Sindicato               5000 non-null   str
 6   Operadora               5000 non-null   str
 7   Linha                   5000 non-null   str
 8   N_Carro                 5000 non-null   int64
 9   N_Validador             5000 non-null   int64
 10  Vl_Linha                5000 non-null   float64
 11  Vl_Trans                5000 non-null   float64
 12  Vl_Subsidio             5000 non-null   float64
dtypes: datetime64[us](2), float64(3), int64(4), str(4)
memory usage: 507.9 KB

Aqui estou mostrando as primeiras linhas

In [100]:
Bu.head()

,Data_do_Processamento,Data_da_Transacao,Descricao_da_Aplicacao,Sentido,N_Validador,Sindicato,Operadora,Linha,N_Carro,N_Validador,Vl_Linha,Vl_Trans,Vl_Subsidio
0,2026-03-15 15:54:08,2026-03-15 15:54:08,80-QR CODE UNITÁRIO,0,77399,BARCAS,Barcas Rio,PXV-PQ - PRAÇAXV X PAQUETA,17007,77399,5.0,5.0,0.0
1,2026-03-15 22:42:20,2026-03-15 22:42:20,80-QR CODE UNITÁRIO,0,77688,METRÔ RIO,Concessao Metroviaria do Rio de Janeiro S. A.,L2 PVN - Estação Pavuna - Metrô,32208,77688,7.9,7.9,0.0
2,2026-03-15 08:13:28,2026-03-15 08:13:28,80-QR CODE UNITÁRIO,0,77361,METRÔ RIO,Concessao Metroviaria do Rio de Janeiro S. A.,L1 SCP - Estação Siqueira Campos - Metrô,17214,77361,7.9,7.9,0.0
3,2026-03-15 09:50:49,2026-03-15 09:50:49,80-QR CODE UNITÁRIO,0,77536,BARCAS,Barcas Rio,PXV-PQ - PRAÇAXV X PAQUETA,13006,77536,5.0,5.0,0.0
4,2026-03-15 09:18:08,2026-03-15 09:18:08,80-QR CODE UNITÁRIO,0,77536,BARCAS,Barcas Rio,PXV-PQ - PRAÇAXV X PAQUETA,13006,77536,5.0,5.0,0.0

Resumo Estático pelo metodo .describe()

Count -> esta contando o numero de registros onde eu limitei dentro do read_csv  coloquei um nrows = 5000
mean -> esta tirando média
std  -> desvio padrao  (o quanto os valores estão espalhados em relação à média.) 
min - > valor Minimo
25% ->  primeiro quartil
50% ->  mediana
75% = > terceiro quartil
Max - e o maximo

In [101]:

Bu.describe().round(0)#round(2) é pra limitar as casas decimais depois do ponto

,Data_do_Processamento,Data_da_Transacao,Sentido,N_Validador,N_Carro,N_Validador,Vl_Linha,Vl_Trans,Vl_Subsidio
count,5000,5000,5000.0,5000.0,5000.0,5000.0,5000.0,5000.0,5000.0
mean,2026-03-15 13:59:12.736000,2026-03-15 13:59:12.736000,0.0,76297.0,20594.0,76297.0,7.0,7.0,0.0
min,2026-03-15 00:01:09,2026-03-15 00:01:09,0.0,42001.0,1208.0,42001.0,5.0,5.0,0.0
25%,2026-03-15 10:34:10.750000,2026-03-15 10:34:10.750000,0.0,77108.0,11207.0,77108.0,5.0,5.0,0.0
50%,2026-03-15 14:05:06.500000,2026-03-15 14:05:06.500000,0.0,77397.0,16109.0,77397.0,8.0,8.0,0.0
75%,2026-03-15 17:21:18.250000,2026-03-15 17:21:18.250000,0.0,77524.0,29107.0,77524.0,8.0,8.0,0.0
max,2026-03-15 23:58:01,2026-03-15 23:58:01,0.0,78329.0,72305.0,78329.0,8.0,8.0,0.0
std,NaN,NaN,0.0,5395.0,15602.0,5395.0,1.0,1.0,0.0

Numero de passageiros por cada concessionaria de transporte publico

In [102]:
Bu["Operadora"].value_counts()

Operadora
Concessao Metroviaria do Rio de Janeiro S. A.    2803
Barcas Rio                                       2197
Name: count, dtype: int64

Abaixo lista o gasto

In [103]:
Bu["Linha"].value_counts()

Linha
PXV-PQ - PRAÇAXV X PAQUETA                         1540
L2 PVN - Estação Pavuna - Metrô                     656
PXV-NIT - PRAÇA XV X ARARIBOIA                      653
L1 CTR - Estação Central - Metrô                    536
L4 JOC - Estação Jardim Oceânico                    228
L1 CNL - Estação Cinelândia - Metrô                 197
L1 GNO - Estação General Osório - metrô             135
L1 CAV - Estação Cardeal Arcoverde - Metrô          126
L1 BTF - Estação Botafogo - Metrô                    66
L1 LMC - Estação Largo do Machado - Metrô            66
L1 GLR - Estação Glória - Metrô                      63
L4 JAH - Estação Jardim de Alah                      54
L2 DCT - Estação Del Castilho - Metrô                53
L4 NSP - Estação Nossa Senhora da Paz                48
L1 SCP - Estação Siqueira Campos - Metrô             47
L1 CTG - Estação Cantagalo - Metrô                   44
L2 MRC - Estação Maracanã - Metrô                    39
L2 CNT - Estação Coelho Neto - Metrô                 39
L1 CTT - Estação Catete - Metrô                      38
L4 SCO - Estação São Conrado                         36
L2 IRJ - Estação Irajá - Metrô                       32
L2 SCR - Estação São Cristovão - Metrô               32
L1 URG - Estação Uruguaiana - Metrô                  28
L2 INH - Estação Inhaúma - Metrô                     26
L1 SPN - Estação Saens Peña - Metrô                  25
L2 MGR - Estação Maria da Graça - Metrô              24
L2 AFB - Estação Acari Fazenda Botafogo - Metrô      22
L1 CRC - Estação Carioca - Metrô                     21
L1 FLA - Estação Flamengo - Metrô                    19
L1 ESA - Estação Estácio - Metrô                     16
L1 AFP - Estação Afonso Pena - Metrô                 11
L2 CLG - Estação Colégio - Metrô                     11
L2 CNO - Estaçao Cidade Nova - metrô                 11
L2 VCV - Estação Vicente de Carvalho - Metrô         10
L4 AQT - Estação Antero de Quental                   10
L2 ERN - Estação Engenho da Rainha - Metrô            9
L1 URI - Estação Uruguai - Metrô                      8
L1 POZ - Estação Praça Onze - Metrô                   5
L2 TCL - Estação Thomaz Coelho - Metrô                4
MAN-IGD - MANGARATIBA X I.GRANDE                      4
L1 PVG - Estação Presidente Vargas - Metrô            2
L1 SFX - Estação São Francisco Xavier - Metrô         2
L2 ERP - Estação Eng Rubens Paiva - Metrô             2
L2 TRG - Estação Triagem - Metrô                      2
Name: count, dtype: int64

Abaixo valor de quanto cada veiculo produziu

In [104]:
# Agrupando por linha para ver faturamento e total de passageiros
analise_linha = Bu.groupby('Linha').agg(
    Faturamento_Total=('Vl_Trans', 'sum'),
    Total_Passageiros=('Vl_Trans', 'count'),
    Qtd_Veiculos_Unicos=('N_Carro', 'nunique') # Conta quantos carros diferentes operaram na linha
).reset_index()
analise_linha

,Linha,Faturamento_Total,Total_Passageiros,Qtd_Veiculos_Unicos
0,L1 AFP - Estação Afonso Pena - Metrô,86.9,11,1
1,L1 BTF - Estação Botafogo - Metrô,521.4,66,7
2,L1 CAV - Estação Cardeal Arcoverde - Metrô,995.4,126,6
3,L1 CNL - Estação Cinelândia - Metrô,1556.3,197,4
4,L1 CRC - Estação Carioca - Metrô,165.9,21,2
5,L1 CTG - Estação Cantagalo - Metrô,347.6,44,4
6,L1 CTR - Estação Central - Metrô,4234.4,536,17
7,L1 CTT - Estação Catete - Metrô,300.2,38,1
8,L1 ESA - Estação Estácio - Metrô,126.4,16,2
9,L1 FLA - Estação Flamengo - Metrô,150.1,19,3
10,L1 GLR - Estação Glória - Metrô,497.7,63,2
11,L1 GNO - Estação General Osório - metrô,1066.5,135,6
12,L1 LMC - Estação Largo do Machado - Metrô,521.4,66,3
13,L1 POZ - Estação Praça Onze - Metrô,39.5,5,1
14,L1 PVG - Estação Presidente Vargas - Metrô,15.8,2,1
15,L1 SCP - Estação Siqueira Campos - Metrô,371.3,47,6
16,L1 SFX - Estação São Francisco Xavier - Metrô,15.8,2,1
17,L1 SPN - Estação Saens Peña - Metrô,197.5,25,3
18,L1 URG - Estação Uruguaiana - Metrô,221.2,28,7
19,L1 URI - Estação Uruguai - Metrô,63.2,8,3
20,L2 AFB - Estação Acari Fazenda Botafogo - Metrô,173.8,22,3
21,L2 CLG - Estação Colégio - Metrô,86.9,11,2
22,L2 CNO - Estaçao Cidade Nova - metrô,86.9,11,2
23,L2 CNT - Estação Coelho Neto - Metrô,308.1,39,2
24,L2 DCT - Estação Del Castilho - Metrô,418.7,53,3
25,L2 ERN - Estação Engenho da Rainha - Metrô,71.1,9,2
26,L2 ERP - Estação Eng Rubens Paiva - Metrô,15.8,2,1
27,L2 INH - Estação Inhaúma - Metrô,205.4,26,2
28,L2 IRJ - Estação Irajá - Metrô,252.8,32,2
29,L2 MGR - Estação Maria da Graça - Metrô,189.6,24,2
30,L2 MRC - Estação Maracanã - Metrô,308.1,39,7
31,L2 PVN - Estação Pavuna - Metrô,5182.4,656,9
32,L2 SCR - Estação São Cristovão - Metrô,252.8,32,5
33,L2 TCL - Estação Thomaz Coelho - Metrô,31.6,4,1
34,L2 TRG - Estação Triagem - Metrô,15.8,2,1
35,L2 VCV - Estação Vicente de Carvalho - Metrô,79.0,10,1
36,L4 AQT - Estação Antero de Quental,79.0,10,2
37,L4 JAH - Estação Jardim de Alah,426.6,54,3
38,L4 JOC - Estação Jardim Oceânico,1801.2,228,7
39,L4 NSP - Estação Nossa Senhora da Paz,379.2,48,6
40,L4 SCO - Estação São Conrado,284.4,36,4
41,MAN-IGD - MANGARATIBA X I.GRANDE,30.8,4,1
42,PXV-NIT - PRAÇA XV X ARARIBOIA,3265.0,653,20
43,PXV-PQ - PRAÇAXV X PAQUETA,7700.0,1540,8

In [105]:
Bu["N_Carro"].value_counts()

N_Carro
13005    387
13006    355
6115     219
17008    186
32208    180
        ...
8305       1
17210      1
14009      1
19212      1
72119      1
Name: count, Length: 176, dtype: int64

Contando quantas vezes um validador se repete

In [106]:
#Bu["N_Validador"].value_counts()

In [107]:
Po.crosstab(Bu["Operadora"], Bu["Sindicato"])

Sindicato                                      BARCAS  METRÔ RIO
Operadora
Barcas Rio                                       2197          0
Concessao Metroviaria do Rio de Janeiro S. A.       0       2803